-- Deploy eshop:040-add_domain to pg

BEGIN;

CREATE DOMAIN NOT_ESPACE_VIDE AS TEXT CHECK(VALUE <> '');

ALTER TABLE "category"
    ALTER COLUMN "name" TYPE NOT_ESPACE_VIDE;
  

ALTER TABLE "product" 
    ALTER COLUMN "name" TYPE NOT_ESPACE_VIDE;

ALTER TABLE "shop" 
    ALTER COLUMN "name" TYPE NOT_ESPACE_VIDE;

ALTER TABLE "user" 
    ALTER COLUMN "username" TYPE NOT_ESPACE_VIDE,
    ALTER COLUMN "first_name" TYPE NOT_ESPACE_VIDE,
    ALTER COLUMN "last_name" TYPE NOT_ESPACE_VIDE,
    ALTER COLUMN "password" TYPE NOT_ESPACE_VIDE;




COMMIT;
