-- Deploy eshop:040-add_domain to pg

BEGIN;

CREATE DOMAIN NOT_EMPTY_SPACE AS TEXT CHECK(VALUE <> '');

ALTER TABLE "category"
    ALTER COLUMN "name" TYPE NOT_EMPTY_SPACE;
  

ALTER TABLE "product" 
    ALTER COLUMN "name" TYPE NOT_EMPTY_SPACE;

ALTER TABLE "shop" 
    ALTER COLUMN "name" TYPE NOT_EMPTY_SPACE,
    ALTER COLUMN "adress" TYPE NOT_EMPTY_SPACE;

ALTER TABLE "user" 
    ALTER COLUMN "username" TYPE NOT_EMPTY_SPACE,
    ALTER COLUMN "first_name" TYPE NOT_EMPTY_SPACE,
    ALTER COLUMN "last_name" TYPE NOT_EMPTY_SPACE,
    ALTER COLUMN "password" TYPE NOT_EMPTY_SPACE;




COMMIT;
